#ifndef ROBOTMAP_H
#define ROBOTMAP_H

#include "WPILib.h"

#define DRIVEBASE_LEFTMOTOR_1_PORT 3
#define DRIVEBASE_LEFTMOTOR_2_PORT 4
#define DRIVEBASE_LEFTMOTOR_3_PORT 5

#define DRIVEBASE_RIGHTMOTOR_1_PORT 0
#define DRIVEBASE_RIGHTMOTOR_2_PORT 1
#define DRIVEBASE_RIGHTMOTOR_3_PORT 2

#define FRONT_OMNI_PORT 0, 1
#define BACK_OMNI_PORT 2, 3

#define FRONT_OMNI_ID 0
#define BACK_OMNI_ID 1

#define SHIFTER_PORT 4, 5

#define COMPRESSOR_PORT 0

#define OI_JOYSTICK_LEFT_PORT 0
#define OI_JOYSTICK_RIGHT_PORT 1

#endif
